services:
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: maria_root_pw
      MARIADB_USER: maria
      MARIADB_PASSWORD: maria_user_pw
      MARIADB_DATABASE: marine
    network_mode: host
    command: --default-authentication-plugin=mysql_native_password --skip-grant-tables
    volumes:
      - db:/var/lib/mysql
    # ports:
    #   - 33066:3306
    # command: /etc/mysql/setup.sh

  adminer:
    image: adminer
    restart: unless-stopped
    network_mode: host

volumes:
  db:
